server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user_service"
    username: root
    password: 1410

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.example: INFO
jwt:
  signerKey: "IjXchw5FLoEbS63K+DFhTARvpWL4jUGCWF6Wux6S5If/1y/LgJxhMqaF6A/ij"
  valid-duration: 3600 # in second



